/**
 * Glossary - Vietnamese explanations for PMBOK ITTO items.
 * Used as tooltip content when hovering over any input, tool, or output.
 * Key matching is case-insensitive and supports partial/fuzzy matching.
 */
const glossary = {

    // ===== COMMON INPUTS =====
    "Project charter": "Điều lệ dự án — Tài liệu chính thức cho phép dự án tồn tại, cung cấp quyền hạn cho PM sử dụng nguồn lực tổ chức. Bao gồm mục đích, mục tiêu cấp cao, các ràng buộc và giả định chính.",
    "Business documents": "Tài liệu kinh doanh — Bao gồm Business Case (phân tích lợi ích-chi phí, lý do đầu tư) và Benefits Management Plan (kế hoạch quản lý lợi ích kỳ vọng từ dự án).",
    "Business case": "Phương án kinh doanh — Phân tích kinh tế chứng minh tính khả thi của dự án, bao gồm phân tích lợi ích, chi phí, rủi ro và các phương án thay thế.",
    "Benefits management plan": "Kế hoạch quản lý lợi ích — Mô tả cách thức và thời điểm lợi ích của dự án sẽ được thực hiện, đo lường và duy trì.",
    "Agreements": "Thỏa thuận/Hợp đồng — Các thỏa thuận chính thức bao gồm hợp đồng, biên bản ghi nhớ (MOU), thư đồng ý, thỏa thuận cấp dịch vụ (SLA).",
    "Enterprise environmental factors": "Yếu tố môi trường doanh nghiệp (EEF) — Các điều kiện không nằm trong tầm kiểm soát của nhóm dự án: văn hóa tổ chức, cơ sở hạ tầng, điều kiện thị trường, quy định pháp luật, hệ thống CNTT hiện có.",
    "Organizational process assets": "Tài sản quy trình tổ chức (OPA) — Các kế hoạch, quy trình, chính sách, thủ tục, và cơ sở kiến thức của tổ chức (bài học kinh nghiệm, dữ liệu lịch sử, mẫu biểu).",
    "Project management plan": "Kế hoạch quản lý dự án — Tài liệu tổng hợp mô tả cách dự án sẽ được thực hiện, giám sát và kiểm soát. Bao gồm tất cả các kế hoạch quản lý thành phần và các baseline.",
    "Project documents": "Tài liệu dự án — Tất cả tài liệu được tạo ra trong quá trình thực hiện dự án như sổ đăng ký rủi ro, nhật ký vấn đề, bài học kinh nghiệm, v.v.",
    "Work performance data": "Dữ liệu hiệu suất công việc — Các quan sát và đo lường thô được thu thập trong quá trình thực hiện dự án (% hoàn thành, chi phí thực tế, ngày bắt đầu/kết thúc thực tế).",
    "Work performance information": "Thông tin hiệu suất công việc — Dữ liệu hiệu suất đã được phân tích và tổng hợp trong ngữ cảnh cụ thể, ví dụ: tình trạng deliverable, tiến độ so với baseline.",
    "Work performance reports": "Báo cáo hiệu suất công việc — Biểu diễn vật lý hoặc điện tử của thông tin hiệu suất được tổng hợp để ra quyết định, bao gồm báo cáo tình trạng, biên bản, dashboard.",
    "Approved change requests": "Yêu cầu thay đổi đã được phê duyệt — Các thay đổi đã được CCB (Change Control Board) xem xét và chấp thuận, sẵn sàng để thực hiện.",
    "Change requests": "Yêu cầu thay đổi — Đề xuất chính thức để sửa đổi bất kỳ tài liệu, deliverable hoặc baseline nào. Bao gồm: hành động khắc phục, phòng ngừa, sửa lỗi.",
    "Deliverables": "Sản phẩm bàn giao — Bất kỳ sản phẩm, kết quả, hoặc năng lực duy nhất và có thể xác minh được, cần được tạo ra để hoàn thành quy trình, giai đoạn hoặc dự án.",
    "Verified deliverables": "Sản phẩm bàn giao đã xác minh — Deliverables đã hoàn thành và được kiểm tra tính chính xác thông qua quy trình Control Quality.",
    "Accepted deliverables": "Sản phẩm bàn giao đã chấp nhận — Deliverables đáp ứng tiêu chí chấp nhận và được khách hàng/sponsor chính thức ký nhận.",
    "Procurement documentation": "Tài liệu mua sắm — Tất cả tài liệu liên quan đến quá trình mua sắm: hợp đồng, SOW, đề xuất của nhà thầu, tiêu chí đánh giá.",
    "Seller proposals": "Đề xuất của nhà thầu — Các đề xuất (kỹ thuật và thương mại) do nhà cung cấp gửi để đáp ứng yêu cầu mua sắm của dự án.",
    "Project funding requirements": "Yêu cầu tài trợ dự án — Chi phí dự kiến theo từng giai đoạn, bao gồm cả dự phòng quản lý, dùng để xác định nhu cầu giải ngân.",

    // ===== KNOWLEDGE AREAS =====
    "Project Integration Management": "Quản lý tích hợp dự án — Phối hợp tất cả các quy trình và hoạt động quản lý dự án. Đảm bảo các yếu tố được kết hợp thống nhất để đạt mục tiêu dự án.",
    "Project Scope Management": "Quản lý phạm vi dự án — Đảm bảo dự án bao gồm tất cả và chỉ những công việc cần thiết để hoàn thành dự án thành công.",
    "Project Schedule Management": "Quản lý tiến độ dự án — Quản lý việc hoàn thành dự án đúng thời hạn thông qua lập kế hoạch, ước lượng, phát triển và kiểm soát lịch trình.",
    "Project Cost Management": "Quản lý chi phí dự án — Lập kế hoạch, ước tính, ngân sách và kiểm soát chi phí để dự án hoàn thành trong ngân sách đã phê duyệt.",
    "Project Quality Management": "Quản lý chất lượng dự án — Đảm bảo dự án đáp ứng nhu cầu mà dự án được thực hiện, bao gồm tất cả hoạt động về chính sách, mục tiêu và trách nhiệm chất lượng.",
    "Project Resource Management": "Quản lý nguồn lực dự án — Xác định, thu nhận và quản lý các nguồn lực cần thiết (nhân sự, thiết bị, vật tư) để hoàn thành dự án thành công.",
    "Project Communications Management": "Quản lý truyền thông dự án — Đảm bảo thông tin dự án được lập kế hoạch, thu thập, phân phối, lưu trữ và kiểm soát kịp thời và phù hợp.",
    "Project Risk Management": "Quản lý rủi ro dự án — Lập kế hoạch, xác định, phân tích, lên phương án ứng phó và giám sát rủi ro dự án nhằm tăng xác suất và tác động của sự kiện tích cực, giảm tiêu cực.",
    "Project Procurement Management": "Quản lý mua sắm dự án — Mua hoặc thu nhận sản phẩm, dịch vụ hoặc kết quả cần thiết từ bên ngoài nhóm dự án.",
    "Project Stakeholder Management": "Quản lý các bên liên quan — Xác định và quản lý những người/tổ chức có thể ảnh hưởng hoặc bị ảnh hưởng bởi dự án, đảm bảo sự tham gia hiệu quả.",

    // ===== PROCESSES (Vietnamese tooltips for table hover) =====
    "4.1 Develop Project Charter": "Xây dựng Điều lệ dự án — Phát triển tài liệu chính thức cho phép dự án tồn tại và cung cấp quyền hạn cho PM sử dụng nguồn lực.",
    "4.2 Develop Project Management Plan": "Xây dựng Kế hoạch quản lý dự án — Xác định, chuẩn bị và phối hợp tất cả các thành phần kế hoạch thành một tài liệu tổng hợp.",
    "4.3 Direct and Manage Project Work": "Chỉ đạo và Quản lý công việc — Lãnh đạo và thực hiện công việc đã được xác định trong kế hoạch quản lý dự án.",
    "4.4 Manage Project Knowledge": "Quản lý Kiến thức dự án — Sử dụng kiến thức hiện có và tạo kiến thức mới để đạt mục tiêu dự án và đóng góp vào học tập tổ chức.",
    "4.5 Monitor and Control Project Work": "Giám sát và Kiểm soát công việc — Theo dõi, đánh giá và báo cáo tiến độ tổng thể để đạt mục tiêu hiệu suất.",
    "4.6 Perform Integrated Change Control": "Kiểm soát Thay đổi tích hợp — Xem xét tất cả yêu cầu thay đổi, phê duyệt và quản lý thay đổi đối với deliverables, tài liệu và kế hoạch.",
    "4.7 Close Project or Phase": "Đóng dự án hoặc Giai đoạn — Hoàn tất tất cả hoạt động để chính thức kết thúc dự án hoặc giai đoạn.",
    "5.1 Plan Scope Management": "Lập kế hoạch Quản lý phạm vi — Tạo kế hoạch mô tả cách phạm vi sẽ được xác định, xác nhận và kiểm soát.",
    "5.2 Collect Requirements": "Thu thập Yêu cầu — Xác định, tài liệu hóa và quản lý nhu cầu và yêu cầu của các bên liên quan để đạt mục tiêu.",
    "5.3 Define Scope": "Xác định Phạm vi — Phát triển mô tả chi tiết về dự án và sản phẩm.",
    "5.4 Create WBS": "Tạo WBS — Phân chia deliverables và công việc thành các thành phần nhỏ hơn, dễ quản lý hơn.",
    "5.5 Validate Scope": "Xác nhận Phạm vi — Chính thức chấp nhận các deliverables đã hoàn thành của dự án.",
    "5.6 Control Scope": "Kiểm soát Phạm vi — Giám sát trạng thái phạm vi và quản lý thay đổi đối với baseline phạm vi.",
    "6.1 Plan Schedule Management": "Lập kế hoạch Quản lý tiến độ — Thiết lập chính sách, thủ tục và tài liệu cho việc lập kế hoạch, phát triển và kiểm soát tiến độ.",
    "6.2 Define Activities": "Xác định Hoạt động — Xác định và tài liệu hóa các hành động cụ thể cần thực hiện để tạo ra deliverables.",
    "6.3 Sequence Activities": "Sắp xếp trình tự Hoạt động — Xác định và tài liệu hóa mối quan hệ giữa các hoạt động dự án.",
    "6.4 Estimate Activity Durations": "Ước lượng Thời gian hoạt động — Ước tính số lượng thời gian cần thiết để hoàn thành từng hoạt động với nguồn lực ước tính.",
    "6.5 Develop Schedule": "Phát triển Tiến độ — Phân tích chuỗi hoạt động, thời gian, nguồn lực và ràng buộc để tạo mô hình tiến độ.",
    "6.6 Control Schedule": "Kiểm soát Tiến độ — Giám sát trạng thái dự án để cập nhật tiến độ và quản lý thay đổi baseline tiến độ.",
    "7.1 Plan Cost Management": "Lập kế hoạch Quản lý chi phí — Xác định cách chi phí dự án sẽ được ước tính, ngân sách hóa, quản lý, giám sát và kiểm soát.",
    "7.2 Estimate Costs": "Ước tính Chi phí — Phát triển ước tính gần đúng về nguồn lực tiền tệ cần thiết để hoàn thành công việc dự án.",
    "7.3 Determine Budget": "Xác định Ngân sách — Tổng hợp chi phí ước tính của từng hoạt động để thiết lập baseline chi phí được phê duyệt.",
    "7.4 Control Costs": "Kiểm soát Chi phí — Giám sát trạng thái dự án để cập nhật chi phí và quản lý thay đổi baseline chi phí.",
    "8.1 Plan Quality Management": "Lập kế hoạch Quản lý chất lượng — Xác định yêu cầu và tiêu chuẩn chất lượng cho dự án và deliverables.",
    "8.2 Manage Quality": "Quản lý Chất lượng — Chuyển kế hoạch chất lượng thành hoạt động thực thi, kết hợp chính sách chất lượng của tổ chức vào dự án.",
    "8.3 Control Quality": "Kiểm soát Chất lượng — Giám sát và ghi nhận kết quả thực hiện hoạt động chất lượng để đánh giá hiệu suất và đề xuất thay đổi.",
    "9.1 Plan Resource Management": "Lập kế hoạch Quản lý nguồn lực — Xác định cách ước tính, thu nhận, quản lý và sử dụng nguồn lực vật chất và nhóm.",
    "9.2 Estimate Activity Resources": "Ước tính Nguồn lực hoạt động — Ước tính nguồn lực nhóm, loại và số lượng vật liệu, thiết bị cần thiết.",
    "9.3 Acquire Resources": "Thu nhận Nguồn lực — Có được thành viên nhóm, cơ sở vật chất, thiết bị, vật liệu, nguồn cung cấp cần thiết.",
    "9.4 Develop Team": "Phát triển Nhóm — Cải thiện năng lực, tương tác và môi trường làm việc nhóm để nâng cao hiệu suất dự án.",
    "9.5 Manage Team": "Quản lý Nhóm — Theo dõi hiệu suất thành viên, cung cấp phản hồi, giải quyết vấn đề và quản lý thay đổi nhóm.",
    "9.6 Control Resources": "Kiểm soát Nguồn lực — Đảm bảo nguồn lực được phân bổ và sử dụng đúng kế hoạch, thực hiện hành động khắc phục khi cần.",
    "10.1 Plan Communications Management": "Lập kế hoạch Quản lý truyền thông — Phát triển phương pháp tiếp cận phù hợp cho hoạt động truyền thông dự án.",
    "10.2 Manage Communications": "Quản lý Truyền thông — Đảm bảo việc thu thập, tạo, phân phối, lưu trữ, truy xuất và xử lý thông tin dự án kịp thời.",
    "10.3 Monitor Communications": "Giám sát Truyền thông — Đảm bảo nhu cầu thông tin của dự án và các bên liên quan được đáp ứng.",
    "11.1 Plan Risk Management": "Lập kế hoạch Quản lý rủi ro — Xác định cách thực hiện các hoạt động quản lý rủi ro cho dự án.",
    "11.2 Identify Risks": "Xác định Rủi ro — Xác định rủi ro dự án cá nhân và nguồn rủi ro tổng thể, tài liệu hóa đặc điểm của chúng.",
    "11.3 Perform Qualitative Risk Analysis": "Phân tích Rủi ro định tính — Đánh giá ưu tiên rủi ro bằng cách đánh giá xác suất xảy ra và tác động, cùng các đặc điểm khác.",
    "11.4 Perform Quantitative Risk Analysis": "Phân tích Rủi ro định lượng — Phân tích bằng số tác động kết hợp của các rủi ro đã xác định lên mục tiêu dự án tổng thể.",
    "11.5 Plan Risk Responses": "Lập kế hoạch Ứng phó rủi ro — Phát triển các phương án, chiến lược và hành động để giải quyết rủi ro tổng thể và từng rủi ro cụ thể.",
    "11.6 Implement Risk Responses": "Thực hiện Ứng phó rủi ro — Triển khai các kế hoạch ứng phó rủi ro đã được thỏa thuận.",
    "11.7 Monitor Risks": "Giám sát Rủi ro — Giám sát việc thực hiện ứng phó rủi ro, theo dõi rủi ro đã xác định, xác định rủi ro mới.",
    "12.1 Plan Procurement Management": "Lập kế hoạch Quản lý mua sắm — Tài liệu hóa quyết định mua sắm, xác định phương pháp tiếp cận và nhà cung cấp tiềm năng.",
    "12.2 Conduct Procurements": "Thực hiện Mua sắm — Nhận phản hồi từ nhà cung cấp, lựa chọn và trao hợp đồng.",
    "12.3 Control Procurements": "Kiểm soát Mua sắm — Quản lý mối quan hệ mua sắm, giám sát hiệu suất hợp đồng, thực hiện thay đổi và sửa chữa.",
    "13.1 Identify Stakeholders": "Xác định Các bên liên quan — Xác định thường xuyên các bên liên quan và phân tích lợi ích, sự tham gia, ảnh hưởng và tác động.",
    "13.2 Plan Stakeholder Engagement": "Lập kế hoạch Gắn kết bên liên quan — Phát triển phương pháp để gắn kết các bên liên quan dựa trên nhu cầu, kỳ vọng và tác động.",
    "13.3 Manage Stakeholder Engagement": "Quản lý Gắn kết bên liên quan — Giao tiếp và làm việc với các bên liên quan để đáp ứng nhu cầu và kỳ vọng, giải quyết vấn đề.",
    "13.4 Monitor Stakeholder Engagement": "Giám sát Gắn kết bên liên quan — Giám sát mối quan hệ với các bên liên quan và điều chỉnh chiến lược gắn kết.",

    // ===== COMMON DOCUMENT ITEMS =====
    "Assumption log": "Sổ nhật ký giả định — Ghi lại tất cả các giả định và ràng buộc trong suốt vòng đời dự án. Các giả định cần được xác nhận hoặc bác bỏ khi dự án tiến triển.",
    "Issue log": "Nhật ký vấn đề — Ghi nhận và theo dõi tất cả các vấn đề phát sinh trong dự án. Mỗi vấn đề bao gồm: mô tả, người phụ trách, ngày phát sinh, trạng thái.",
    "Change log": "Nhật ký thay đổi — Danh sách toàn diện ghi lại tất cả các yêu cầu thay đổi trong dự án và trạng thái hiện tại của chúng.",
    "Lessons learned register": "Sổ bài học kinh nghiệm — Ghi chép kiến thức thu được trong dự án về những gì đã làm tốt, những gì cần cải thiện, được cập nhật liên tục trong suốt dự án.",
    "Risk register": "Sổ đăng ký rủi ro — Danh sách các rủi ro đã xác định, bao gồm mô tả, nguyên nhân, xác suất, tác động, chiến lược ứng phó, và người chịu trách nhiệm.",
    "Risk report": "Báo cáo rủi ro — Tóm tắt tình trạng rủi ro tổng thể của dự án, bao gồm các rủi ro cá nhân quan trọng nhất và mức độ rủi ro tổng thể.",
    "Stakeholder register": "Sổ đăng ký các bên liên quan — Thông tin về các bên liên quan: vai trò, quan tâm, kỳ vọng, mức độ ảnh hưởng, mức độ tham gia hiện tại và mong muốn.",
    "Requirements documentation": "Tài liệu yêu cầu — Mô tả cách các yêu cầu riêng lẻ đáp ứng nhu cầu kinh doanh. Bao gồm yêu cầu chức năng, phi chức năng, chất lượng.",
    "Requirements traceability matrix": "Ma trận truy vết yêu cầu — Bảng liên kết yêu cầu sản phẩm từ nguồn gốc đến deliverable, đảm bảo mỗi yêu cầu được theo dõi xuyên suốt vòng đời dự án.",
    "Milestone list": "Danh sách cột mốc — Liệt kê các cột mốc quan trọng của dự án và cho biết chúng là bắt buộc hay tùy chọn.",
    "Project schedule": "Lịch trình dự án — Mô hình trình bày các hoạt động với ngày kế hoạch, thời lượng, cột mốc và tài nguyên. Thường hiển thị dưới dạng Gantt chart.",
    "Project communications": "Truyền thông dự án — Các tài liệu truyền thông như báo cáo hiệu suất, cập nhật tình trạng, trình bày cho các bên liên quan.",
    "Quality reports": "Báo cáo chất lượng — Tài liệu tóm tắt các vấn đề chất lượng, đề xuất cải tiến và các khuyến nghị về hành động khắc phục.",
    "Quality metrics": "Chỉ số chất lượng — Mô tả thuộc tính dự án/sản phẩm và cách quy trình Control Quality sẽ xác minh sự tuân thủ.",
    "Quality control measurements": "Kết quả đo lường kiểm soát chất lượng — Kết quả đo lường cụ thể từ hoạt động kiểm soát chất lượng, dùng để đánh giá hiệu suất quy trình.",
    "Project team assignments": "Phân công nhóm dự án — Tài liệu ghi nhận vai trò và trách nhiệm của từng thành viên trong nhóm dự án.",
    "Resource breakdown structure": "Cơ cấu phân chia nguồn lực (RBS) — Biểu đồ phân cấp nguồn lực theo loại và danh mục, giúp lập kế hoạch và kiểm soát công việc.",
    "Resource calendars": "Lịch nguồn lực — Xác định thời gian nguồn lực (nhân sự, thiết bị) có sẵn cho dự án, bao gồm ngày nghỉ, ca làm việc.",
    "Resource requirements": "Yêu cầu nguồn lực — Xác định loại và số lượng nguồn lực cần thiết cho từng work package hoặc hoạt động.",
    "Activity list": "Danh sách hoạt động — Tất cả các hoạt động cần thực hiện trong dự án, được xác định từ phân rã WBS.",
    "Activity attributes": "Thuộc tính hoạt động — Thông tin chi tiết về từng hoạt động: mô tả, ràng buộc, giả định, người thực hiện, vị trí.",
    "Basis of estimates": "Cơ sở ước tính — Tài liệu hỗ trợ giải thích cách thức ước tính được lập, bao gồm giả định, ràng buộc, phạm vi ước tính, mức độ tin cậy.",
    "Cost estimates": "Ước tính chi phí — Đánh giá định lượng chi phí dự kiến cho nguồn lực cần thiết để hoàn thành hoạt động dự án.",
    "Duration estimates": "Ước tính thời lượng — Đánh giá định lượng về số lượng thời gian cần thiết để hoàn thành hoạt động với nguồn lực ước tính.",
    "Cost forecasts": "Dự báo chi phí — Ước tính chi phí hoàn thành (EAC) được tính toán dựa trên hiệu suất thực tế, giúp dự đoán tổng chi phí cuối cùng.",
    "Schedule forecasts": "Dự báo lịch trình — Ước tính hoặc dự đoán về tình trạng lịch trình trong tương lai dựa trên hiệu suất hiện tại.",
    "Test and evaluation documents": "Tài liệu kiểm tra và đánh giá — Mô tả các hoạt động kiểm tra chất lượng sản phẩm, bao gồm kế hoạch test, kịch bản test, kết quả test.",
    "Physical resource assignments": "Phân công nguồn lực vật chất — Ghi nhận việc phân bổ các nguồn lực vật chất (thiết bị, vật liệu, cơ sở vật chất) cho dự án.",
    "Team performance assessments": "Đánh giá hiệu suất nhóm — Đánh giá hiệu quả hoạt động tổng thể của nhóm dự án, bao gồm kỹ năng, năng lực và tương tác nhóm.",
    "Team charter": "Điều lệ nhóm — Tài liệu thiết lập giá trị, thỏa thuận và hướng dẫn hoạt động của nhóm dự án. Bao gồm quy tắc làm việc, cách ra quyết định.",
    "Project scope statement": "Tuyên bố phạm vi dự án — Mô tả chi tiết phạm vi dự án, deliverable chính, giả định và ràng buộc. Là cơ sở cho các quyết định trong tương lai.",
    "Scope baseline": "Baseline phạm vi — Phiên bản đã được phê duyệt của tuyên bố phạm vi, WBS và từ điển WBS, dùng làm cơ sở so sánh.",
    "Schedule baseline": "Baseline lịch trình — Phiên bản đã được phê duyệt của lịch trình dự án, dùng làm cơ sở so sánh với kết quả thực tế.",
    "Cost baseline": "Baseline chi phí — Ngân sách dự án đã được phê duyệt theo từng giai đoạn thời gian, không bao gồm dự phòng quản lý. Dùng làm cơ sở đo lường hiệu suất.",
    "Performance measurement baseline": "Baseline đo lường hiệu suất (PMB) — Kết hợp baseline phạm vi, lịch trình và chi phí. Dùng để đo lường và quản lý hiệu suất dự án.",

    // ===== COMMON TOOLS & TECHNIQUES =====
    "Expert judgment": "Phán đoán chuyên gia — Ý kiến từ các cá nhân hoặc nhóm có kiến thức chuyên môn, kinh nghiệm trong lĩnh vực liên quan. Nguồn: chuyên gia nội bộ, tư vấn, hiệp hội nghề nghiệp, PMO.",
    "Meetings": "Cuộc họp — Các buổi thảo luận có cấu trúc để trao đổi thông tin, ra quyết định, giải quyết vấn đề. Bao gồm: kick-off, status, retrospective, steering committee.",
    "Data gathering": "Thu thập dữ liệu — Các kỹ thuật thu thập thông tin bao gồm: brainstorming, phỏng vấn, nhóm tập trung, bảng câu hỏi, benchmarking, checklist.",
    "Data analysis": "Phân tích dữ liệu — Các kỹ thuật phân tích như: phân tích thay thế, phân tích chi phí-lợi ích, phân tích giá trị thu được (EVM), phân tích xu hướng, phân tích sai lệch.",
    "Data representation": "Biểu diễn dữ liệu — Các cách trình bày dữ liệu trực quan: biểu đồ dòng chảy, sơ đồ tư duy, ma trận, biểu đồ nhân quả, histogram.",
    "Decision making": "Ra quyết định — Các phương pháp lựa chọn: bỏ phiếu, phân tích quyết định đa tiêu chí, quyết định độc đoán. Mục đích: đạt được đồng thuận nhóm.",
    "Interpersonal and team skills": "Kỹ năng giao tiếp và làm việc nhóm — Bao gồm: quản lý xung đột, tạo động lực, đàm phán, xây dựng nhóm, lãnh đạo, nhận thức chính trị, tạo ảnh hưởng.",
    "Project management information system": "Hệ thống thông tin quản lý dự án (PMIS) — Công cụ phần mềm tổng hợp lịch trình, chi phí, báo cáo. Ví dụ: MS Project, Jira, Primavera.",
    "Communication technology": "Công nghệ truyền thông — Các phương tiện truyền đạt thông tin: email, họp trực tuyến, chia sẻ tài liệu, phần mềm cộng tác (Teams, Slack).",
    "Communication methods": "Phương pháp truyền thông — Cách thức chia sẻ thông tin: tương tác (interactive), đẩy (push), kéo (pull). Chọn phương pháp phù hợp với loại thông tin.",
    "Inspection": "Kiểm tra — Xem xét và đo lường sản phẩm hoặc kết quả để xác minh chúng tuân thủ các tiêu chuẩn. Bao gồm: review, kiểm thử, walkthrough.",
    "Audits": "Kiểm toán — Quy trình độc lập để xác định xem các hoạt động dự án có tuân thủ chính sách, quy trình và thủ tục không.",
    "Decomposition": "Phân rã — Kỹ thuật chia nhỏ phạm vi dự án và deliverables thành các thành phần nhỏ hơn, dễ quản lý hơn (WBS → Work Package → Activity).",
    "Rolling wave planning": "Lập kế hoạch cuốn chiếu — Kỹ thuật lập kế hoạch chi tiết cho công việc sắp tới, lập kế hoạch cấp cao cho công việc trong tương lai xa.",
    "Precedence diagramming method": "Phương pháp sơ đồ ưu tiên (PDM) — Kỹ thuật tạo mạng lịch trình sử dụng các nút biểu diễn hoạt động, nối bằng mối quan hệ logic (FS, FF, SS, SF).",
    "Leads and lags": "Thời gian đẩy nhanh và trễ — Lead: cho phép hoạt động kế tiếp bắt đầu sớm hơn. Lag: thêm thời gian chờ giữa các hoạt động liên tiếp.",
    "Analogous estimating": "Ước tính tương tự — Sử dụng dữ liệu từ dự án tương tự trước đó làm cơ sở ước tính. Nhanh, ít tốn kém nhưng độ chính xác thấp hơn.",
    "Parametric estimating": "Ước tính tham số — Sử dụng mối quan hệ thống kê giữa dữ liệu lịch sử và các biến khác để ước tính (ví dụ: chi phí/m², giờ công/chức năng).",
    "Three-point estimating": "Ước tính ba điểm — Sử dụng 3 giá trị: lạc quan (O), bi quan (P), khả dĩ nhất (M). Công thức PERT: (O + 4M + P) / 6.",
    "Bottom-up estimating": "Ước tính từ dưới lên — Ước tính chi tiết từng thành phần nhỏ nhất rồi tổng hợp lên. Độ chính xác cao nhất nhưng tốn thời gian nhất.",
    "Critical path method": "Phương pháp đường găng (CPM) — Xác định chuỗi hoạt động dài nhất trong lịch trình, quyết định thời gian ngắn nhất để hoàn thành dự án. Float = 0 trên đường găng.",
    "Resource optimization": "Tối ưu hóa nguồn lực — Bao gồm: Resource Leveling (điều chỉnh lịch trình theo ràng buộc nguồn lực) và Resource Smoothing (điều chỉnh trong phạm vi float).",
    "Schedule compression": "Nén lịch trình — Crashing: thêm nguồn lực để rút ngắn thời gian (tăng chi phí). Fast tracking: thực hiện song song các hoạt động (tăng rủi ro).",
    "Earned value analysis": "Phân tích giá trị thu được (EVA) — So sánh giá trị công việc thực hiện với kế hoạch. Các chỉ số: PV, EV, AC, SV, CV, SPI, CPI.",
    "Variance analysis": "Phân tích sai lệch — So sánh kết quả thực tế với baseline để xác định mức độ chênh lệch và nguyên nhân. Áp dụng cho phạm vi, lịch trình, chi phí.",
    "Trend analysis": "Phân tích xu hướng — Xem xét hiệu suất dự án theo thời gian để xác định xem đang cải thiện hay suy giảm, từ đó dự báo tương lai.",
    "Root cause analysis": "Phân tích nguyên nhân gốc (RCA) — Kỹ thuật xác định nguyên nhân cơ bản của vấn đề hoặc rủi ro, sử dụng 5 Whys, biểu đồ Ishikawa.",
    "Alternatives analysis": "Phân tích các phương án thay thế — Đánh giá và so sánh nhiều phương án khác nhau để chọn giải pháp tối ưu nhất.",
    "Cost-benefit analysis": "Phân tích chi phí-lợi ích — So sánh chi phí dự kiến với lợi ích dự kiến để đánh giá tính khả thi và giá trị của dự án/quyết định.",
    "Cost of quality": "Chi phí chất lượng (COQ) — Tổng chi phí tuân thủ (phòng ngừa + kiểm tra) và chi phí không tuân thủ (lỗi nội bộ + lỗi bên ngoài).",
    "Cost aggregation": "Tổng hợp chi phí — Tổng hợp ước tính chi phí từ work package lên cấp cao hơn theo cấu trúc WBS để xây dựng baseline chi phí.",
    "Reserve analysis": "Phân tích dự phòng — Đánh giá mức dự phòng (contingency reserve cho rủi ro đã biết, management reserve cho rủi ro chưa biết).",
    "Funding limit reconciliation": "Điều chỉnh giới hạn tài trợ — Điều chỉnh chi tiêu dự án để phù hợp với giới hạn giải ngân của nguồn tài trợ.",
    "Financing": "Tài chính — Xác định và thu xếp nguồn vốn cho dự án từ các nguồn bên trong và bên ngoài tổ chức.",
    "To-complete performance index": "Chỉ số hiệu suất để hoàn thành (TCPI) — Hiệu suất chi phí cần đạt được cho phần công việc còn lại để đạt mục tiêu. TCPI = (BAC - EV) / (BAC - AC).",
    "Change control tools": "Công cụ kiểm soát thay đổi — Phần mềm và thủ tục hỗ trợ quản lý cấu hình và thay đổi. Ví dụ: Git, JIRA, ServiceNow.",
    "Product analysis": "Phân tích sản phẩm — Kỹ thuật xác định phạm vi bằng cách phân tích sản phẩm: phân tích giá trị, phân tích chức năng, phân tích hệ thống.",
    "Brainstorming": "Động não — Kỹ thuật thu thập ý tưởng từ nhóm một cách tự do, không phê phán, nhằm tạo ra nhiều ý tưởng đa dạng nhất có thể.",
    "Interviews": "Phỏng vấn — Cuộc trao đổi trực tiếp hoặc gián tiếp với các bên liên quan để thu thập thông tin về yêu cầu, rủi ro, kỳ vọng.",
    "Focus groups": "Nhóm tập trung — Cuộc thảo luận có điều phối với nhóm nhỏ các bên liên quan đã được chọn trước để thu thập ý kiến chuyên sâu.",
    "Questionnaires and surveys": "Bảng câu hỏi và khảo sát — Công cụ thu thập thông tin từ số lượng lớn người tham gia, phù hợp khi phân tán địa lý.",
    "Benchmarking": "So sánh chuẩn — So sánh thực tiễn, quy trình, sản phẩm của dự án với các tổ chức tương tự hoặc tiêu chuẩn ngành để xác định cải tiến.",
    "Facilitation": "Điều phối — Kỹ năng dẫn dắt nhóm đạt quyết định thành công, đảm bảo mọi người tham gia hiệu quả, quản lý động lực nhóm.",
    "Conflict management": "Quản lý xung đột — Kỹ năng giải quyết bất đồng: Collaborate/Problem solve, Compromise, Withdraw, Smooth/Accommodate, Force/Direct.",
    "Negotiation": "Đàm phán — Kỹ năng thảo luận để đạt thỏa thuận giữa các bên có lợi ích khác nhau. Áp dụng trong mua sắm, phân bổ nguồn lực, giải quyết xung đột.",
    "Multicriteria decision analysis": "Phân tích quyết định đa tiêu chí — Sử dụng ma trận quyết định với nhiều tiêu chí có trọng số để đánh giá và xếp hạng các phương án.",
    "Voting": "Bỏ phiếu — Phương pháp ra quyết định tập thể: unanimity (nhất trí), majority (đa số), plurality (đa số tương đối).",
    "Colocation": "Đồng vị trí — Đặt các thành viên nhóm dự án làm việc tại cùng một địa điểm vật lý để tăng cường giao tiếp và cộng tác (war room).",
    "Virtual teams": "Nhóm ảo — Nhóm người có chung mục tiêu nhưng làm việc từ xa, ít hoặc không gặp trực tiếp. Sử dụng công nghệ truyền thông để cộng tác.",
    "Training": "Đào tạo — Hoạt động nâng cao năng lực cho thành viên nhóm: khóa học, workshop, coaching, mentoring, on-the-job training.",
    "Recognition and rewards": "Công nhận và khen thưởng — Hệ thống khen thưởng chính thức và không chính thức để tạo động lực, khuyến khích hành vi tích cực trong nhóm.",
    "Pre-assignment": "Chỉ định trước — Nguồn lực đã được xác định và cam kết cho dự án trước khi dự án bắt đầu (do yêu cầu hợp đồng, kỹ năng đặc biệt).",
    "Problem solving": "Giải quyết vấn đề — Quy trình có cấu trúc: xác định vấn đề → phân tích nguyên nhân → đề xuất giải pháp → thực hiện → xác minh kết quả.",
    "Advertising": "Quảng cáo — Thông báo công khai về cơ hội đấu thầu/mua sắm cho các nhà cung cấp tiềm năng thông qua các kênh truyền thông phù hợp.",
    "Bidder conferences": "Hội nghị nhà thầu — Cuộc họp với tất cả các nhà thầu tiềm năng để đảm bảo họ hiểu rõ và thống nhất về yêu cầu mua sắm.",
    "Claims administration": "Quản lý khiếu nại — Quy trình xử lý tranh chấp giữa bên mua và bên bán, bao gồm thương lượng, hòa giải, trọng tài.",
    "Source selection analysis": "Phân tích lựa chọn nguồn cung — Đánh giá và lựa chọn nhà cung cấp dựa trên tiêu chí như: giá thấp nhất, chất lượng, năng lực kỹ thuật.",
    "Knowledge management": "Quản lý kiến thức — Quy trình thu thập, tổ chức, chia sẻ và ứng dụng kiến thức trong tổ chức để cải thiện hiệu quả dự án.",
    "Information management": "Quản lý thông tin — Công cụ và kỹ thuật lưu trữ, truy xuất, phân phối thông tin dự án: PMIS, hệ thống tài liệu, cơ sở dữ liệu.",
    "Communication requirements analysis": "Phân tích yêu cầu truyền thông — Xác định nhu cầu thông tin của các bên liên quan: loại thông tin, tần suất, định dạng, phương pháp truyền tải.",
    "Communication models": "Mô hình truyền thông — Khung lý thuyết mô tả quá trình truyền thông: người gửi, thông điệp, kênh, người nhận, phản hồi, nhiễu.",
    "Stakeholder analysis": "Phân tích các bên liên quan — Kỹ thuật thu thập và phân tích thông tin về các bên liên quan để xác định mức độ quan tâm, ảnh hưởng và chiến lược quản lý.",
    "SWOT analysis": "Phân tích SWOT — Đánh giá Strengths (Điểm mạnh), Weaknesses (Điểm yếu), Opportunities (Cơ hội), Threats (Mối đe dọa) để xác định rủi ro.",
    "Risk categorization": "Phân loại rủi ro — Nhóm các rủi ro theo nguồn gốc (kỹ thuật, bên ngoài, tổ chức, quản lý dự án) sử dụng RBS (Risk Breakdown Structure).",
    "Probability and impact matrix": "Ma trận xác suất và tác động — Bảng kết hợp xác suất xảy ra với mức độ tác động để xếp hạng ưu tiên rủi ro (Cao, Trung bình, Thấp).",
    "Sensitivity analysis": "Phân tích độ nhạy — Xác định rủi ro nào có tác động lớn nhất đến dự án. Thường biểu diễn bằng Tornado diagram.",
    "Decision tree analysis": "Phân tích cây quyết định — Sơ đồ mô tả các lựa chọn, xác suất và hậu quả để hỗ trợ ra quyết định có tính đến rủi ro và giá trị kỳ vọng (EMV).",
    "Simulations": "Mô phỏng — Kỹ thuật phân tích định lượng (thường dùng Monte Carlo) chạy nhiều kịch bản ngẫu nhiên để xác định phạm vi kết quả có thể.",
    "Strategies for threats": "Chiến lược ứng phó rủi ro tiêu cực — Escalate (Leo thang), Avoid (Né tránh), Transfer (Chuyển giao - bảo hiểm), Mitigate (Giảm nhẹ), Accept (Chấp nhận).",
    "Strategies for opportunities": "Chiến lược ứng phó rủi ro tích cực — Escalate (Leo thang), Exploit (Khai thác), Share (Chia sẻ), Enhance (Tăng cường), Accept (Chấp nhận).",
    "Contingent response strategies": "Chiến lược ứng phó dự phòng — Phản ứng chỉ được thực hiện khi điều kiện kích hoạt (trigger) xảy ra, thường sử dụng fallback plan.",
    "Design for X": "Thiết kế cho X (DfX) — Tập hợp hướng dẫn kỹ thuật áp dụng trong thiết kế sản phẩm để tối ưu: độ tin cậy, khả năng sản xuất, chi phí, an toàn.",
    "Quality improvement methods": "Phương pháp cải tiến chất lượng — Các phương pháp như PDCA (Plan-Do-Check-Act), Six Sigma, Lean để cải tiến liên tục quy trình.",
    "Statistical sampling": "Lấy mẫu thống kê — Chọn một phần của tổng thể để kiểm tra, giảm chi phí kiểm soát chất lượng trong khi vẫn đảm bảo tính đại diện.",
    "Organizational theory": "Lý thuyết tổ chức — Kiến thức về cách con người, nhóm và tổ chức hoạt động, giúp PM lãnh đạo nhóm hiệu quả hơn.",
    "Prompt lists": "Danh sách gợi ý — Danh sách các danh mục rủi ro được xác định trước để hỗ trợ việc nhận dạng rủi ro một cách toàn diện.",
    "Schedule network analysis": "Phân tích mạng lịch trình — Kỹ thuật tổng hợp tạo ra lịch trình dự án, bao gồm phương pháp đường găng, tối ưu nguồn lực và mô phỏng.",
    "Agile release planning": "Lập kế hoạch phát hành Agile — Cung cấp lịch trình phát hành cấp cao dựa trên product backlog, tốc độ nhóm và mục tiêu release.",
    "Make-or-buy analysis": "Phân tích tự làm hay mua — Đánh giá chi phí, lợi ích, rủi ro để quyết định nên tự thực hiện hay thuê bên ngoài cho công việc cụ thể.",
    "Market research": "Nghiên cứu thị trường — Thu thập thông tin về năng lực nhà cung cấp, giá cả thị trường, xu hướng ngành để hỗ trợ quyết định mua sắm.",
    "Proposal evaluation": "Đánh giá đề xuất — Xem xét và chấm điểm các đề xuất của nhà thầu dựa trên tiêu chí lựa chọn đã xác định trước.",
    "Test and inspection planning": "Lập kế hoạch kiểm tra và kiểm thử — Xác định phương pháp, tiêu chí và lịch trình cho việc kiểm tra và kiểm thử sản phẩm.",
    "Flowcharts": "Lưu đồ — Biểu đồ mô tả trình tự các bước trong quy trình, giúp xác định các bước có giá trị gia tăng và các điểm cần cải tiến.",
    "Context diagram": "Sơ đồ ngữ cảnh — Biểu diễn trực quan phạm vi sản phẩm bằng cách hiển thị hệ thống kinh doanh và cách các bên tương tác với nó.",
    "Prototypes": "Nguyên mẫu — Phiên bản thử nghiệm của sản phẩm để thu thập phản hồi sớm từ các bên liên quan trước khi phát triển chính thức.",
    "Mind mapping": "Sơ đồ tư duy — Kỹ thuật trực quan sắp xếp ý tưởng từ một khái niệm trung tâm, giúp tổ chức thông tin và phát hiện mối quan hệ.",
    "Affinity diagrams": "Biểu đồ tương đồng — Kỹ thuật nhóm các ý tưởng theo chủ đề chung, thường dùng sau brainstorming để tổ chức và phân loại kết quả.",
    "Cause-and-effect diagrams": "Biểu đồ nhân quả (Ishikawa) — Sơ đồ xương cá xác định nguyên nhân tiềm ẩn của vấn đề, phân loại theo: Con người, Phương pháp, Máy móc, Vật liệu, Môi trường.",
    "Control charts": "Biểu đồ kiểm soát — Đồ thị theo thời gian hiển thị giới hạn kiểm soát trên/dưới để xác định quy trình có ổn định và dự đoán được không.",
    "Histograms": "Biểu đồ tần suất — Đồ thị cột hiển thị phân bổ tần suất của dữ liệu, giúp xác định mẫu hình và các vấn đề chất lượng tiềm ẩn.",
    "Scatter diagrams": "Biểu đồ phân tán — Đồ thị hiển thị mối quan hệ giữa hai biến, giúp xác định mối tương quan (dương, âm hoặc không tương quan).",
    "Stakeholder engagement assessment matrix": "Ma trận đánh giá mức độ tham gia các bên liên quan — So sánh mức độ tham gia hiện tại (C) với mong muốn (D): Unaware, Resistant, Neutral, Supportive, Leading.",
    "Individual and team assessments": "Đánh giá cá nhân và nhóm — Công cụ đánh giá kỹ năng, năng lực, phong cách làm việc của thành viên: MBTI, DISC, StrengthsFinder.",
    "Representations of uncertainty": "Biểu diễn tính không chắc chắn — Các phương pháp mô hình hóa rủi ro: phân phối xác suất (tam giác, beta, normal) cho mô phỏng Monte Carlo.",
    "Influence diagrams": "Sơ đồ ảnh hưởng — Biểu diễn đồ họa các mối quan hệ nhân quả, thứ tự thời gian và các mối quan hệ khác giữa các biến và kết quả.",

    // ===== COMMON OUTPUTS =====
    "Project management plan updates": "Cập nhật kế hoạch quản lý dự án — Các thay đổi được phê duyệt đối với kế hoạch quản lý dự án hoặc các kế hoạch thành phần.",
    "Project documents updates": "Cập nhật tài liệu dự án — Các thay đổi được thực hiện đối với tài liệu dự án như sổ rủi ro, nhật ký vấn đề, bài học kinh nghiệm.",
    "Organizational process assets updates": "Cập nhật tài sản quy trình tổ chức — Cải tiến quy trình, mẫu biểu, bài học kinh nghiệm được cập nhật vào kho kiến thức tổ chức.",
    "Enterprise environmental factors updates": "Cập nhật yếu tố môi trường doanh nghiệp — Thay đổi về kỹ năng nhân sự, kinh nghiệm, năng lực được cập nhật vào hệ thống tổ chức.",
    "Scope management plan": "Kế hoạch quản lý phạm vi — Mô tả cách phạm vi được xác định, phát triển, giám sát, kiểm soát và xác nhận trong dự án.",
    "Requirements management plan": "Kế hoạch quản lý yêu cầu — Mô tả cách yêu cầu được phân tích, tài liệu hóa và quản lý trong suốt dự án.",
    "Schedule management plan": "Kế hoạch quản lý lịch trình — Thiết lập tiêu chí và hoạt động để phát triển, giám sát và kiểm soát lịch trình dự án.",
    "Cost management plan": "Kế hoạch quản lý chi phí — Mô tả cách chi phí dự án được lập kế hoạch, cấu trúc và kiểm soát.",
    "Quality management plan": "Kế hoạch quản lý chất lượng — Mô tả cách chính sách chất lượng được thực hiện, bao gồm tiêu chuẩn, quy trình kiểm soát chất lượng.",
    "Resource management plan": "Kế hoạch quản lý nguồn lực — Hướng dẫn cách phân loại, phân bổ, quản lý và giải phóng nguồn lực dự án.",
    "Communications management plan": "Kế hoạch quản lý truyền thông — Xác định cách thức, thời điểm, tần suất và người chịu trách nhiệm truyền thông trong dự án.",
    "Risk management plan": "Kế hoạch quản lý rủi ro — Mô tả cách quản lý rủi ro được cấu trúc và thực hiện: phương pháp, vai trò, ngân sách, thời điểm.",
    "Procurement management plan": "Kế hoạch quản lý mua sắm — Mô tả cách nhóm dự án sẽ mua hàng hóa/dịch vụ từ bên ngoài, bao gồm loại hợp đồng, tiêu chí đánh giá.",
    "Stakeholder engagement plan": "Kế hoạch tham gia các bên liên quan — Chiến lược quản lý và tăng cường sự tham gia hiệu quả của các bên liên quan.",
    "Change management plan": "Kế hoạch quản lý thay đổi — Mô tả cách yêu cầu thay đổi được quản lý, bao gồm quy trình, vai trò CCB, mức độ ủy quyền.",
    "Configuration management plan": "Kế hoạch quản lý cấu hình — Mô tả cách thông tin về cấu hình sản phẩm được ghi nhận và cập nhật, đảm bảo tính nhất quán.",
    "Final report": "Báo cáo cuối cùng — Tóm tắt hiệu suất dự án: so sánh mục tiêu ban đầu với kết quả thực tế, tổng hợp bài học kinh nghiệm.",
    "Closed procurements": "Mua sắm đã đóng — Xác nhận chính thức rằng tất cả công việc và deliverable trong hợp đồng đã được hoàn thành và chấp nhận.",
    "Selected sellers": "Nhà cung cấp đã chọn — Nhà thầu được chọn dựa trên kết quả đánh giá đề xuất và tiêu chí lựa chọn đã xác định.",
    "Bid documents": "Hồ sơ mời thầu — Tài liệu cung cấp cho nhà thầu tiềm năng: RFP (Yêu cầu đề xuất), RFQ (Yêu cầu báo giá), RFI (Yêu cầu thông tin), IFB (Mời thầu).",
    "Procurement statement of work": "Tuyên bố công việc mua sắm (SOW) — Mô tả chi tiết sản phẩm/dịch vụ cần mua, đủ để nhà thầu xác định khả năng cung cấp.",
    "Source selection criteria": "Tiêu chí lựa chọn nguồn cung — Các tiêu chí đánh giá nhà thầu: giá, năng lực kỹ thuật, kinh nghiệm, rủi ro, tiến độ.",
    "Make-or-buy decisions": "Quyết định tự làm hay mua — Kết quả phân tích xác định công việc nào tự thực hiện, công việc nào thuê bên ngoài.",
    "Independent cost estimates": "Ước tính chi phí độc lập — Ước tính chi phí từ bên thứ ba để so sánh với đề xuất của nhà thầu, đảm bảo tính hợp lý.",
    "Procurement strategy": "Chiến lược mua sắm — Phương pháp tiếp cận tổng thể cho mua sắm: phương thức giao hàng, loại hợp đồng, giai đoạn mua sắm.",
    "Procurement documentation updates": "Cập nhật tài liệu mua sắm — Cập nhật hợp đồng, SOW, lịch thanh toán, kết quả đánh giá hiệu suất nhà thầu."
};
